### ISSUE TITLE
unable to run script

### ISSUE THREAD

**Issue by jakejh** [hugheylab/coding_sprint_workflowr#2]
When I try to source the analysis_setup.R script, I get the following:

Error in wflow_open(analysisFilename, change_wd = FALSE, edit_in_rstudio = FALSE) : 
  could not find function "wflow_open"

Have you verified the instructions work for yourself?

**Comment by jakejh** [comment]
This is probably because I first tried it in MS Code, not RStudio. Ideally would be something that works in any editor and R terminal, not just RStudio.

**Comment by JSchoenbachler** [comment]
Fixed as of https://github.com/hugheylab/coding_sprint_workflowr/commit/b21d1bc4290b145ac5dc2e3cf7a13e5f8fa7fc27

I wasn't calling the library at the beginning.
