### ISSUE TITLE
other README issues

### ISSUE THREAD

**Issue by jakejh** [hugheylab/coding_sprint_workflowr#3]
in README:

1. When I try to run `workflowr::wflow_build()` in MS Code, I get the following error:
Error in (function (files = NULL, make = is.null(files), update = FALSE,  : Pandoc is not installed. Please use RStudio or install pandoc manually
1. Step 6 contains multiple steps.
1. What exactly does "edit analysis/sample_analysis.Rmd script" mean? How am I supposed to edit it?
1. If I add functions to the code directory, how do I make them accessible to each analysis_*.rmd file? Similarly, how will each rmd file access data in the data directory?
1. Add cowplot, foreach, and doParallel to the Imports.

**Comment by jakejh** [comment]
Also:
- On step 9, don't I need to git add and commit before pushing?
- Where is the instruction for dealing with changes to lab personnel?

**Comment by JSchoenbachler** [comment]
- [x] When I try to run workflowr::wflow_build() in MS Code, I get the following error: Error in (function (files = NULL, make = is.null(files), update = FALSE, : Pandoc is not installed. Please use RStudio or install pandoc manually
- [x] Step 6 contains multiple steps.
- [x] What exactly does "edit analysis/sample_analysis.Rmd script" mean? How am I supposed to edit it?
- [x] If I add functions to the code directory, how do I make them accessible to each analysis_*.rmd file? Similarly, how will each rmd file access data in the data directory?
- [x] Add cowplot, foreach, and doParallel to the Imports.
- [x] On step 9, don't I need to git add and commit before pushing?
- [x] Where is the instruction for dealing with changes to lab personnel?

**Comment by JSchoenbachler** [comment]
Fixed as of https://github.com/hugheylab/coding_sprint_workflowr/commit/b21d1bc4290b145ac5dc2e3cf7a13e5f8fa7fc27
