### ISSUE TITLE
change `labNames` for clarity

### ISSUE THREAD

**Issue by jakejh** [hugheylab/coding_sprint_workflowr#6]
Nit-picky, but the variable doesn't contain the names of labs. I suggest `persons` and `person` as the `for` iterated variable.

https://github.com/hugheylab/coding_sprint_workflowr/blob/af9de001e76347028a39b3cb9924b4fb3c5233f6/code/analysis_setup.R#L2

**Comment by JSchoenbachler** [comment]
Fixed as of https://github.com/hugheylab/coding_sprint_workflowr/commit/b21d1bc4290b145ac5dc2e3cf7a13e5f8fa7fc27
