### ISSUE TITLE
use sprintf for readability

### ISSUE THREAD

**Issue by jakejh** [hugheylab/coding_sprint_workflowr#7]
https://github.com/hugheylab/coding_sprint_workflowr/blob/af9de001e76347028a39b3cb9924b4fb3c5233f6/code/analysis_setup.R#L13

**Comment by JSchoenbachler** [comment]
Fixed as of https://github.com/hugheylab/coding_sprint_workflowr/commit/37fc02388038498df8d07033f28849c4b7c65d3e
